language: go

go:
- 1.14.x

deploy:
  provider: releases
  api_key: $GTOKEN
  file: 
    - vorteil_windows-x86.zip
    - vorteil_linux-x86.tar.gz
    - vorteil_darwin-x86.tar.gz
  skip_cleanup: true
  draft: true
  on:
    tags: true

jobs:
  include:
    - stage: test
      script: scripts/test.sh
    - stage: build
      os: linux
      script:
        - scripts/keychain.sh 
        - scripts/build.sh
        - zip vorteil_windows-x86.zip vorteil.exe && rm vorteil.exe
        - tar -zcvf vorteil_linux-x86.tar.gz vorteil && rm vorteil
    - stage: build
      os: osx
      script: 
        - scripts/build.sh
        - codesign -s $OSX_APP_SIGN_ID -v --timestamp --options runtime vorteil
        - tar -zcvf vorteil_darwin-x86.tar.gz vorteil && rm vorteil
