language: go

go:
- 1.14.x

deploy:
  provider: releases
  api_key: $GTOKEN
  file: 
    - windows/vorteil.exe
    - linux/vorteil
    - darwin/vorteil
  skip_cleanup: true
  draft: true
  on:
    tags: true

jobs:
  include:
    - stage: test
      script: scripts/test.sh
    - stage: build
      script: scripts/build.sh
