language: go

go:
- 1.14.x

deploy:
  provider: releases
  api_key: $GTOKEN
  file: 
    - vorteil_windows-x86.zip
    - vorteil_linux-x86.tar.gz
    - vorteil_darwin-x86.tar.gz
  skip_cleanup: true
  draft: true
  on:
    tags: true

jobs:
  include:
    - stage: test
      script: scripts/test.sh
    - stage: build
      script: scripts/build.sh
